# -*- coding: UTF-8 -*-
from __future__ import unicode_literals
# compatibilidade entre Python2 e 3.

"""
Django settings for sigsis project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

path_pc = '//home/amilcar/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b2$3k_5pcq6#ed&ax+v9iz%k)^q-%-)y!z#jj^45e23*tt+f^5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['http://localhost:8000/sigsis/']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.webdesign',
    'tinymce',
    'sorl.thumbnail',
    'mce_filebrowser',
    'core',
    'widget_tweaks',# biblioteca para customizar elementos do form simulador no template
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'sigsis.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [path_pc + 'sigsis/core/html/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigsis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
DATABASES = {
'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'sigsis',
    'HOST': '127.0.0.1',
    'PORT': '3306',
    'USER': 'admin',
    'PASSWORD': 'admin',
    'TIME_ZONE': 'America/Sao_Paulo'
}}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

# Content-Type header.
 
DEFAULT_CONTENT_TYPE = 'text/html'
 
DEFAULT_CHARSET = 'utf-8'
 
FILE_CHARSET = 'utf-8'
 

USE_I18N = True

USE_L10N = True

#USE_TZ = True # Se deixar dá erro no DB!!!


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
MEDIA_ROOT = path_pc + 'sigsis/core/media/'
MEDIA_URL = '/sigsis/media/'

STATIC_URL = '/sigsis/static/'
STATIC_ROOT = path_pc + 'sigsis/core/static/'
# Additional locations of static files
STATICFILES_DIRS = (path_pc + 'sigsis/core/media',)# é preciso manter a vírgula

TINYMCE_JS_URL = os.path.join(STATIC_URL, 'tiny_mce/tiny_mce.js' )
TINYMCE_JS_ROOT = STATIC_ROOT + 'tiny_mce/'
#TINYMCE_FILEBROWSER = True # com isso não aparece a busca da inserção de imagem no admin
TINYMCE_SPELLCHECKER = True 
#TINYMCE_COMPRESSOR = True # com esse parâmetro não funciona
TINYMCE_DEFAULT_CONFIG = {
'plugins' : "pagebreak, spellchecker, style, layer, table, lists, save, advhr, advimage, advlink, autolink, emotions, iespell, inlinepopups, insertdatetime, preview, media, searchreplace, print, contextmenu, paste, directionality, fullscreen, noneditable, visualchars, nonbreaking, xhtmlxtras, template, wordcount, advlist, autosave, media, visualblocks,",
'theme': "advanced",    
# Theme options
'theme_advanced_buttons1' : "bold,italic,underline,strikethrough,sub,sup,|,removeformat,visualchars,|,justifyleft,justifycenter,justifyright,justifyfull,|,formatselect,fontselect,fontsizeselect,|,forecolor,backcolor,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,|,code,|,fullscreen,|",
'theme_advanced_buttons2' : "tablecontrols,|,hr,|,charmap,image,media,insertfile,anchor,|,search,replace,|",

'theme_advanced_toolbar_location' : "top",
'theme_advanced_toolbar_align' : "left",
'theme_advanced_statusbar_location' : "bottom",
'theme_advanced_resizing' : 'true',
'file_browser_callback': 'mce_filebrowser',
'width': '100%',
'height': '200',
'cleanup_on_startup': True,
'custom_uno_redo_levels': 10,
'nowrap': False,
#'relative_urls': False,
#'paste_text_sticky': True,
#'paste_text_sticky_default' : True,
#'style_formats' : "[{title : 'Bold text', inline : 'strong'},{title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},{title : 'Help', inline : 'strong', classes : 'help'},{title : 'Table styles'},{title : 'Table row 1', selector : 'tr', classes : 'tablerow'}]",
}

#Sessao
SESSION_COOKIE_AGE = 43200 # 12 horas * 60 minutos * 60 segundos
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
